version: '3'

services:
  mongodbrs:
    image: mongo
    hostname: mongodbrs
    restart: always
    container_name: mongodb-replicaset
    volumes:
      - ./scripts/initrs.sh:/scripts/initrs.sh
    ports:
      - 27020:27017
    networks:
      - mongo-network
    command: ['--replSet', 'rs0', '--bind_ip_all']

networks:
  mongo-network:
    driver: bridge