version: '3'

services:
  mongodbtestdb:
    image: mongo
    hostname: mongodbtestdb
    restart: always
    container_name: mongodbtestdb
    volumes:
      - ./scripts/initrs.sh:/scripts/initrs.sh
    ports:
      - 27020:27017
    networks:
      - mongo-network
    healthcheck:
      test: test $$(echo "rs.initiate().ok || rs.status().ok" | mongo -u mongo -p mongo --quiet) -eq 1
      interval: 10s
      start_period: 30s
    command: ['--replSet', 'rs0', '--bind_ip_all']

networks:
  mongo-network:
    driver: bridge